name: 'Marshal Diff Validator'
description: 'Runs Marshal AI semantic diff validation on a Pull Request'
author: 'Marshal AI Team'
branding:
  icon: check-circle
  color: purple

inputs:
  api-url:
    description: 'Your Marshal API Gateway URL (e.g. https://.../validate_diff)'
    required: true
  api-key:
    description: 'Marshal API key'
    required: true

runs:
  using: 'node16'
  main: 'src/index.js'
